# Generated by Django 4.2.9 on 2024-02-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
