# Generated by Django 4.2.9 on 2024-02-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_category_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price_total',
        ),
    ]
