# Generated by Django 4.2.9 on 2024-02-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_purchases_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, null=True),
        ),
    ]
