# Generated by Django 4.2.9 on 2024-02-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_purchases_price_total_sales_price_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
